// Auto-generated by scripts/generate-content.cjs - do not edit
export const LEARN_LEVELS = [
  {
    "id": "beginner",
    "label": "Basics for Beginners",
    "description": "Never used JSON? Start here."
  },
  {
    "id": "comfortable",
    "label": "Getting Comfortable",
    "description": "Understand structure and patterns."
  },
  {
    "id": "practical",
    "label": "Practical JSON",
    "description": "Real-world usage and APIs."
  },
  {
    "id": "intermediate",
    "label": "Intermediate",
    "description": "Validation, schema, and best practices."
  },
  {
    "id": "advanced",
    "label": "Advanced",
    "description": "JSON Schema, JSONPath, performance."
  },
  {
    "id": "expert",
    "label": "Expert Level",
    "description": "Security, streaming, alternatives."
  }
] as const;

export interface LearnSection {
  id: string;
  level: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
  excerpt?: string;
  keyTerms: string[];
  tryExample?: string;
}

export const LEARN_SECTIONS: LearnSection[] = [
  {
    "id": "what-is-json",
    "level": "beginner",
    "title": "What is JSON?",
    "metaTitle": "What is JSON? A Complete Introduction for Beginners",
    "metaDescription": "JSON (JavaScript Object Notation) is a lightweight data format used by 70%+ of APIs. Learn what JSON is, why it exists, and when to use it.",
    "contentMarkdown": "JSON stands for JavaScript Object Notation. It's a lightweight, text-based format for storing and exchanging data between systems. Created by Douglas Crockford in 2001 and standardized as ECMA-404 and RFC 8259, JSON has become the de facto standard for web APIs—over 70% of public APIs use JSON. Unlike XML, it's human-readable and easy for both humans and machines to parse.",
    "excerpt": "JSON stands for JavaScript Object Notation. It's a lightweight, text-based format for storing and exchanging data between systems. Created by Douglas Crockford in 2001 and standardized as ECMA-404 and",
    "keyTerms": [
      "JSON",
      "data interchange",
      "API",
      "lightweight",
      "text-based"
    ]
  },
  {
    "id": "json-vs-xml-csv",
    "level": "beginner",
    "title": "JSON vs XML vs CSV",
    "contentMarkdown": "JSON is often compared to XML and CSV. XML uses tags and is verbose; JSON is more compact. CSV is flat and great for spreadsheets but poor for nested data. JSON sits in the middle: readable, hierarchical, and widely supported in every programming language.\r\n\r\n```text\r\n// XML (verbose)\r\n<user>\r\n  <name>Alice</name>\r\n  <age>30</age>\r\n</user>\r\n\r\n// JSON (compact)\r\n{\"name\": \"Alice\", \"age\": 30}\r\n\r\n// CSV (flat only)\r\nname,age\r\nAlice,30\r\n```\r\n\r\n- JSON: compact, hierarchical, universal support\r\n- XML: verbose, schema-rich, legacy systems\r\n- CSV: flat, spreadsheet-friendly, no nesting",
    "excerpt": "JSON is often compared to XML and CSV. XML uses tags and is verbose; JSON is more compact. CSV is flat and great for spreadsheets but poor for nested data. JSON sits in the middle: readable, hierarchi",
    "keyTerms": []
  },
  {
    "id": "six-data-types",
    "level": "beginner",
    "title": "The Six JSON Data Types",
    "metaTitle": "JSON Data Types: String, Number, Boolean, Null, Object, Array",
    "metaDescription": "JSON supports exactly six data types. Learn strings, numbers, booleans, null, objects, and arrays with examples.",
    "contentMarkdown": "JSON has exactly six data types. Understanding these is the foundation of working with JSON.\r\n\r\n## String\r\n\r\nA sequence of characters wrapped in double quotes. Use backslash for escaping: `\\\"` for quotes, `\\\\` for backslash, `\\n` for newline.\r\n\r\n```json\r\n\"Hello, World!\"\r\n```\r\n\r\n```json\r\n\"Escaped: \\\"quote\\\" and \\\\backslash\\\\\"\r\n```\r\n\r\n```json\r\n\"Line 1\\nLine 2\"\r\n```\r\n\r\n## Number\r\n\r\nIntegers or decimals. No quotes. Scientific notation allowed.\r\n\r\n```json\r\n42\r\n```\r\n\r\n```text\r\n3.14\r\n-100\r\n1.5e10\r\n```\r\n\r\n## Boolean\r\n\r\nLogical values. Must be lowercase: true or false.\r\n\r\n```json\r\ntrue\r\n```\r\n\r\n```json\r\nfalse\r\n```\r\n\r\n## Null\r\n\r\nRepresents absence of value. Always lowercase null.\r\n\r\n```json\r\nnull\r\n```\r\n\r\n## Object\r\n\r\nUnordered collection of key-value pairs in curly braces. Keys must be strings.\r\n\r\n```json\r\n{\"name\": \"Alice\", \"age\": 30, \"active\": true}\r\n```\r\n\r\n## Array\r\n\r\nOrdered list of values in square brackets. Values can be any type.\r\n\r\n```json\r\n[\"red\", \"green\", \"blue\"]\r\n```\r\n\r\n```json\r\n[1, 2, 3, 4, 5]\r\n```\r\n\r\n```json\r\n[true, false, null]\r\n```",
    "excerpt": "JSON has exactly six data types. Understanding these is the foundation of working with JSON.\r\n\r\n\r\n\r\nA sequence of characters wrapped in double quotes. Use backslash for escaping: \\\" for quotes, \\\\ for",
    "keyTerms": [
      "string",
      "number",
      "boolean",
      null,
      "object",
      "array"
    ]
  },
  {
    "id": "syntax-rules",
    "level": "beginner",
    "title": "JSON Syntax Rules — The Golden Rules",
    "metaTitle": "JSON Syntax Rules: Keys, Quotes, Commas, and More",
    "metaDescription": "Master JSON syntax: double quotes for keys and strings, no trailing commas, no comments. Avoid common JSON mistakes.",
    "contentMarkdown": "Follow these rules or your JSON will be invalid.\r\n\r\n- Keys must be strings in double quotes — not single quotes\r\n- Strings must use double quotes — single quotes are invalid\r\n- No trailing commas after the last item in objects or arrays\r\n- No comments allowed — JSON has no `//` or `/* */` support\r\n- `true`, `false`, and `null` must be lowercase\r\n- Numbers have no quotes: use `42`, not `\"42\"`\r\n- Commas separate items; no comma after the last item\r\n\r\n```text\r\n// ✅ Valid JSON\r\n{\"name\": \"Alice\", \"age\": 30}\r\n\r\n// ❌ Invalid: single quotes\r\n{'name': 'Alice'}\r\n\r\n// ❌ Invalid: trailing comma\r\n{\"name\": \"Alice\",}\r\n\r\n// ❌ Invalid: unquoted key\r\n{name: \"Alice\"}\r\n```",
    "excerpt": "Follow these rules or your JSON will be invalid.\r\n\r\n- Keys must be strings in double quotes — not single quotes\r\n- Strings must use double quotes — single quotes are invalid\r\n- No trailing commas afte",
    "keyTerms": []
  },
  {
    "id": "first-json-object",
    "level": "beginner",
    "title": "Your First JSON Object",
    "contentMarkdown": "A simple object has keys and values. Think of it like a dictionary or a form: each field has a name (key) and a value.\r\n\r\n```json\r\n{\r\n  \"name\": \"Alice\",\r\n  \"age\": 30,\r\n  \"email\": \"alice@example.com\",\r\n  \"active\": true\r\n}\r\n```",
    "excerpt": "A simple object has keys and values. Think of it like a dictionary or a form: each field has a name (key) and a value.",
    "keyTerms": [],
    "tryExample": "{\"name\": \"Your Name\", \"favoriteColor\": \"blue\", \"luckyNumber\": 7}"
  },
  {
    "id": "objects-arrays-depth",
    "level": "comfortable",
    "title": "Objects and Arrays in Depth",
    "contentMarkdown": "Objects group related data; arrays hold lists. You can nest them: objects inside arrays, arrays inside objects. There's no limit to how deep you can go (though readability suffers after 3–4 levels).\r\n\r\n```json\r\n{\r\n  \"users\": [\r\n    {\"id\": 1, \"name\": \"Alice\", \"roles\": [\"admin\", \"editor\"]},\r\n    {\"id\": 2, \"name\": \"Bob\", \"roles\": [\"viewer\"]}\r\n  ],\r\n  \"metadata\": {\r\n    \"total\": 2,\r\n    \"page\": 1\r\n  }\r\n}\r\n```",
    "excerpt": "Objects group related data; arrays hold lists. You can nest them: objects inside arrays, arrays inside objects. There's no limit to how deep you can go (though readability suffers after 3–4 levels).",
    "keyTerms": []
  },
  {
    "id": "common-patterns",
    "level": "comfortable",
    "title": "Common JSON Patterns",
    "metaTitle": "Common JSON Patterns: API Responses, Configs, and More",
    "metaDescription": "Learn the most common JSON patterns: list of objects, nested config, key-value lookup. Copy-paste ready examples.",
    "contentMarkdown": "These patterns appear everywhere in real applications.\r\n\r\n## List of Objects (API responses)\r\n\r\nThe most common pattern — an array of uniform objects. Used by almost every REST API.\r\n\r\n```json\r\n[\r\n  {\"id\": 1, \"name\": \"Alice\", \"email\": \"alice@example.com\"},\r\n  {\"id\": 2, \"name\": \"Bob\", \"email\": \"bob@example.com\"}\r\n]\r\n```\r\n\r\n## Nested Configuration\r\n\r\nObjects inside objects for grouping. Perfect for app config, feature flags, and settings.\r\n\r\n```json\r\n{\r\n  \"database\": {\r\n    \"host\": \"localhost\",\r\n    \"port\": 5432,\r\n    \"name\": \"mydb\"\r\n  },\r\n  \"features\": {\r\n    \"darkMode\": true,\r\n    \"notifications\": false\r\n  }\r\n}\r\n```\r\n\r\n## Key-Value Lookup (Dictionary)\r\n\r\nFlat object as a map. Great for currency rates, translations, or status codes.\r\n\r\n```json\r\n{\r\n  \"USD\": 1.0,\r\n  \"EUR\": 0.92,\r\n  \"GBP\": 0.79,\r\n  \"JPY\": 149.50\r\n}\r\n```",
    "excerpt": "These patterns appear everywhere in real applications.\r\n\r\n\r\n\r\nThe most common pattern — an array of uniform objects. Used by almost every REST API.\r\n\r\n\r\n\r\n\r\n\r\nObjects inside objects for grouping. Perf",
    "keyTerms": []
  },
  {
    "id": "valid-vs-invalid",
    "level": "comfortable",
    "title": "Valid vs Invalid JSON",
    "contentMarkdown": "Invalid JSON will cause parsing to fail. Common errors: forgetting quotes, using single quotes, trailing commas, or JavaScript-only values like `undefined` or `NaN` (which aren't valid JSON).\r\n\r\n```text\r\n// ✅ Valid\r\n{\"a\": 1, \"b\": [2, 3]}\r\n\r\n// ❌ Trailing comma\r\n{\"a\": 1, \"b\": 2,}\r\n\r\n// ❌ Single quotes (JavaScript OK, JSON invalid)\r\n{'a': 1}\r\n\r\n// ❌ Unquoted key\r\n{a: 1}\r\n\r\n// ❌ undefined is not valid JSON\r\n{\"a\": undefined}\r\n```",
    "excerpt": "Invalid JSON will cause parsing to fail. Common errors: forgetting quotes, using single quotes, trailing commas, or JavaScript-only values like undefined or NaN (which aren't valid JSON).",
    "keyTerms": []
  },
  {
    "id": "json-in-apis",
    "level": "practical",
    "title": "JSON in REST APIs",
    "metaTitle": "How JSON is Used in REST APIs — Complete Guide",
    "metaDescription": "Learn how JSON powers REST APIs. Request and response examples, Content-Type headers, and parsing in JavaScript, Python, and more.",
    "contentMarkdown": "REST APIs send and receive JSON. The client sends JSON in the request body (e.g., POST), and the server responds with JSON. Always set `Content-Type: application/json`.\r\n\r\n- GET returns JSON in the body\r\n- POST/PUT/PATCH send JSON in the body\r\n- Content-Type: application/json header\r\n- Status codes: 200 OK, 201 Created, 400 Bad Request, 404 Not Found\r\n\r\n```json\r\n{\r\n  \"data\": [\r\n    {\"id\": 1, \"title\": \"First Post\"},\r\n    {\"id\": 2, \"title\": \"Second Post\"}\r\n  ],\r\n  \"meta\": {\r\n    \"page\": 1,\r\n    \"total\": 42\r\n  }\r\n}\r\n```",
    "excerpt": "REST APIs send and receive JSON. The client sends JSON in the request body (e.g., POST), and the server responds with JSON. Always set Content-Type: application/json.\r\n\r\n- GET returns JSON in the body",
    "keyTerms": []
  },
  {
    "id": "parse-stringify",
    "level": "practical",
    "title": "Parsing and Stringifying",
    "metaTitle": "JSON.parse() and JSON.stringify() — Complete Guide",
    "metaDescription": "Convert JSON text to objects with JSON.parse. Convert objects to JSON with JSON.stringify. Learn revivers, replacers, and pretty-printing.",
    "contentMarkdown": "In JavaScript: `JSON.parse()` converts a JSON string into an object. `JSON.stringify()` does the opposite. Other languages have equivalents (`json.loads`/`json.dumps` in Python, `json_decode`/`json_encode` in PHP).\r\n\r\n```javascript\r\n// Parse: string → object\r\nconst str = '{\"name\":\"Alice\",\"age\":30}';\r\nconst obj = JSON.parse(str);\r\nconsole.log(obj.name); // \"Alice\"\r\n\r\n// Stringify: object → string\r\nconst json = JSON.stringify(obj);\r\n// Pretty-print with 2-space indent\r\nconst pretty = JSON.stringify(obj, null, 2);\r\n```",
    "excerpt": "In JavaScript: JSON.parse() converts a JSON string into an object. JSON.stringify() does the opposite. Other languages have equivalents (json.loads/json.dumps in Python, jsondecode/jsonencode in PHP).",
    "keyTerms": []
  },
  {
    "id": "pretty-vs-minified",
    "level": "practical",
    "title": "Pretty Print vs Minified",
    "contentMarkdown": "Pretty-printed JSON uses indentation and newlines for readability—ideal for config files and debugging. Minified JSON removes whitespace to reduce size—ideal for APIs and network transfer. Same data, different formatting.\r\n\r\n```text\r\n// Pretty (readable)\r\n{\r\n  \"name\": \"Alice\",\r\n  \"age\": 30\r\n}\r\n\r\n// Minified (compact)\r\n{\"name\":\"Alice\",\"age\":30}\r\n```",
    "excerpt": "Pretty-printed JSON uses indentation and newlines for readability—ideal for config files and debugging. Minified JSON removes whitespace to reduce size—ideal for APIs and network transfer. Same data,",
    "keyTerms": []
  },
  {
    "id": "json-schema-basics",
    "level": "intermediate",
    "title": "JSON Schema — Structure Your Data",
    "metaTitle": "JSON Schema Tutorial: Validate and Define JSON Structure",
    "metaDescription": "JSON Schema defines and validates JSON structure. Learn type checking, required fields, patterns, and validation tools.",
    "contentMarkdown": "JSON Schema is a vocabulary for annotating and validating JSON documents. It defines allowed types, required properties, formats (email, date), and custom rules. Tools like Ajv (JavaScript) and jsonschema (Python) validate data against schemas.\r\n\r\n```json\r\n{\r\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\r\n  \"type\": \"object\",\r\n  \"properties\": {\r\n    \"name\": {\"type\": \"string\"},\r\n    \"age\": {\"type\": \"number\", \"minimum\": 0},\r\n    \"email\": {\"type\": \"string\", \"format\": \"email\"}\r\n  },\r\n  \"required\": [\"name\", \"email\"]\r\n}\r\n```",
    "excerpt": "JSON Schema is a vocabulary for annotating and validating JSON documents. It defines allowed types, required properties, formats (email, date), and custom rules. Tools like Ajv (JavaScript) and jsonsc",
    "keyTerms": []
  },
  {
    "id": "escaping-special-chars",
    "level": "intermediate",
    "title": "Escaping and Special Characters",
    "contentMarkdown": "Inside JSON strings, certain characters must be escaped with a backslash: `\\\"` (quote), `\\\\` (backslash), `\\b` (backspace), `\\f` (form feed), `\\n` (newline), `\\r` (carriage return), `\\t` (tab). Unicode can be written as `\\uXXXX`.\r\n\r\n```json\r\n\"Quote: \\\"Hello\\\"\"\r\n```\r\n\r\n```json\r\n\"Tab: col1\\tcol2\"\r\n```\r\n\r\n```json\r\n\"Newline: line1\\nline2\"\r\n```\r\n\r\n```json\r\n\"Unicode: \\u00A9 (copyright)\"\r\n```",
    "excerpt": "Inside JSON strings, certain characters must be escaped with a backslash: \\\" (quote), \\\\ (backslash), \\b (backspace), \\f (form feed), \\n (newline), \\r (carriage return), \\t (tab). Unicode can be writt",
    "keyTerms": []
  },
  {
    "id": "common-mistakes",
    "level": "intermediate",
    "title": "Common JSON Mistakes and Fixes",
    "metaTitle": "Top JSON Mistakes: Trailing Commas, Quotes, and How to Fix",
    "metaDescription": "Avoid the most common JSON errors: trailing commas, single quotes, unquoted keys, and JavaScript-only values. Quick fixes and validation tips.",
    "contentMarkdown": "Most JSON errors fall into a few categories. Know them and fix them fast.\r\n\r\n- Trailing comma: Remove the last comma before `}` or `]`\r\n- Single quotes: Replace with double quotes\r\n- Unquoted keys: Wrap all keys in double quotes\r\n- undefined/NaN: Use `null` or omit the property\r\n- Comments: JSON doesn't support them—remove or use a separate config",
    "excerpt": "Most JSON errors fall into a few categories. Know them and fix them fast.\r\n\r\n- Trailing comma: Remove the last comma before } or ]\r\n- Single quotes: Replace with double quotes\r\n- Unquoted keys: Wrap a",
    "keyTerms": []
  },
  {
    "id": "jsonpath",
    "level": "advanced",
    "title": "JSONPath — Query JSON Like SQL",
    "metaTitle": "JSONPath Tutorial: Query and Extract JSON Data",
    "metaDescription": "JSONPath lets you query JSON like XPath for XML. Select nested values with $, ., .., and []. RFC 9535 standard.",
    "contentMarkdown": "JSONPath is a query language for JSON. Use it to extract specific values from nested structures. `$` is the root, `.` accesses children, `..` does recursive descent, `[]` selects by index or condition.\r\n\r\n```text\r\n// Data\r\n{\"users\": [{\"name\": \"Alice\", \"score\": 95}, {\"name\": \"Bob\", \"score\": 87}]}\r\n\r\n// JSONPath examples\r\n$.users[0].name     → \"Alice\"\r\n$.users[*].name     → [\"Alice\", \"Bob\"]\r\n$.users[?(@.score > 90)].name → [\"Alice\"]\r\n```",
    "excerpt": "JSONPath is a query language for JSON. Use it to extract specific values from nested structures. $ is the root, . accesses children, .. does recursive descent, [] selects by index or condition.",
    "keyTerms": []
  },
  {
    "id": "performance-large-files",
    "level": "advanced",
    "title": "Performance: Large JSON Files",
    "contentMarkdown": "Parsing huge JSON files can freeze the browser or exhaust memory. Use streaming parsers (e.g., JSONStream in Node, ijson in Python) to process incrementally. For files over 10–50MB, consider splitting or using a binary format.\r\n\r\n- Streaming parsers process chunk-by-chunk\r\n- Avoid loading entire file into memory\r\n- Consider pagination or chunked API responses\r\n- Binary alternatives: MessagePack, BSON for very large data",
    "excerpt": "Parsing huge JSON files can freeze the browser or exhaust memory. Use streaming parsers (e.g., JSONStream in Node, ijson in Python) to process incrementally. For files over 10–50MB, consider splitting",
    "keyTerms": []
  },
  {
    "id": "security",
    "level": "expert",
    "title": "JSON Security Best Practices",
    "metaTitle": "JSON Security: Injection, Deserialization, and Validation",
    "metaDescription": "Secure your JSON handling: prevent injection, validate with schema, limit depth, sanitize output. Enterprise security guide.",
    "contentMarkdown": "Untrusted JSON can be dangerous. Validate with a schema, limit parsing depth, and never `eval()` JSON (use `JSON.parse`). Be wary of ReDoS in schema patterns. Whitelist allowed fields in APIs.\r\n\r\n- Always use `JSON.parse()`, never `eval()`\r\n- Validate with JSON Schema before trusting data\r\n- Limit object depth to prevent stack overflow\r\n- Sanitize output to prevent XSS when rendering\r\n- Use parameterized queries—never concatenate JSON into SQL",
    "excerpt": "Untrusted JSON can be dangerous. Validate with a schema, limit parsing depth, and never eval() JSON (use JSON.parse). Be wary of ReDoS in schema patterns. Whitelist allowed fields in APIs.\r\n\r\n- Always",
    "keyTerms": []
  },
  {
    "id": "json-alternatives",
    "level": "expert",
    "title": "JSON Alternatives: When to Use What",
    "contentMarkdown": "JSON5 adds comments and trailing commas. JSONC is JSON with comments (used by VS Code config). YAML is more readable for config. MessagePack is binary and faster. Choose based on use case.\r\n\r\n- JSON5: JSON + comments, trailing commas, unquoted keys\r\n- YAML: Human-friendly config, supports comments\r\n- MessagePack: Binary, smaller, faster parsing\r\n- Protocol Buffers: Strong typing, schema-first, binary",
    "excerpt": "JSON5 adds comments and trailing commas. JSONC is JSON with comments (used by VS Code config). YAML is more readable for config. MessagePack is binary and faster. Choose based on use case.\r\n\r\n- JSON5:",
    "keyTerms": []
  }
];
