// Auto-generated by scripts/generate-content.cjs - do not edit
export interface PageContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
}
export const PAGES: PageContent[] = [
  {
    "slug": "about",
    "title": "About JSON Prism",
    "metaTitle": "About JSON Prism — Format, Validate, Diff JSON",
    "metaDescription": "JSON Prism is a free, open-source JSON toolkit. Format, validate, diff, and explore JSON in your browser. No data stored. Works offline.",
    "contentMarkdown": "JSON Prism is a free, open-source JSON toolkit that runs entirely in your browser.\r\n\r\n- **Format** — Pretty-print or minify JSON\r\n- **Validate** — Check syntax and structure\r\n- **Diff** — Compare two JSON documents\r\n- **Explore** — Tree view, search, and navigation\r\n\r\nNo data is stored or sent to any server. Everything runs locally. Works offline."
  },
  {
    "slug": "privacy",
    "title": "Privacy Policy",
    "metaTitle": "Privacy Policy — JSON Prism",
    "metaDescription": "JSON Prism processes data locally. No server storage. No analytics by default.",
    "contentMarkdown": "JSON Prism is designed with privacy in mind.\r\n\r\n- **No server storage** — All JSON processing happens in your browser\r\n- **No data sent** — Your JSON is never transmitted to our servers\r\n- **Share links** — When you share, JSON is encoded in the URL (client-side). Large payloads may use optional shortening services\r\n\r\nWe do not collect, store, or sell your data."
  }
];
export const PAGE_SLUGS: string[] = ["about","privacy"];
