// Auto-generated by scripts/generate-content.cjs - do not edit
export interface PageContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
}
export const PAGES: PageContent[] = [
  {
    "slug": "about",
    "title": "About JSON Prism",
    "metaTitle": "About JSON Prism — Format, Validate, Diff JSON",
    "metaDescription": "JSON Prism is a free, open-source JSON toolkit. Format, validate, diff, and explore JSON in your browser. No data stored. Works offline.",
    "contentMarkdown": "JSON Prism is a free, open-source JSON toolkit that runs entirely in your browser.\r\n\r\n- **Format** — Pretty-print or minify JSON\r\n- **Validate** — Check syntax and structure\r\n- **Diff** — Compare two JSON documents\r\n- **Explore** — Tree view, search, and navigation\r\n\r\nNo data is stored or sent to any server. Everything runs locally. Works offline."
  },
  {
    "slug": "privacy",
    "title": "Privacy Policy",
    "metaTitle": "Privacy Policy — JSON Prism",
    "metaDescription": "JSON Prism processes data locally. No server storage by default. No analytics by default.",
    "contentMarkdown": "JSON Prism is designed with privacy in mind.\r\n\r\n- **Local processing** — All JSON parsing, formatting, and viewing happens in your browser\r\n- **No data sent by default** — Your JSON is never transmitted to our servers\r\n- **Share links** — When you share, JSON is encoded directly into the URL fragment (client-side only). Nothing is uploaded\r\n- **Optional short links** — If you click _Create short link_, the already-encoded payload (not your original JSON) is stored on our own Cloudflare KV for **30 days**, then auto-deleted. The short link service is never contacted unless you press that button\r\n\r\nWe do not collect, store, or sell your data."
  }
];
export const PAGE_SLUGS: string[] = ["about","privacy"];
