/**
 * Build-time: reads markdown content from /content
 * Generates strongly typed TS modules for learn, pages, site, and tools.
 * No database - all content lives in the repo.
 */
const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");

const ROOT = process.cwd();

const LEARN_DIR = path.join(ROOT, "content", "learn");
const LEARN_OUT = path.join(ROOT, "src", "lib", "learn-sections.generated.ts");
const PAGES_DIR = path.join(ROOT, "content", "pages");
const PAGES_OUT = path.join(ROOT, "src", "lib", "pages-content.generated.ts");
const SITE_DIR = path.join(ROOT, "content", "site");
const SITE_OUT = path.join(ROOT, "src", "lib", "site-content.generated.ts");
const TOOLS_DIR = path.join(ROOT, "content", "tools");
const TOOLS_OUT = path.join(ROOT, "src", "lib", "tool-content.generated.ts");

const LEVELS = [
  { id: "beginner", label: "Basics for Beginners", description: "Never used JSON? Start here." },
  { id: "comfortable", label: "Getting Comfortable", description: "Understand structure and patterns." },
  { id: "practical", label: "Practical JSON", description: "Real-world usage and APIs." },
  { id: "intermediate", label: "Intermediate", description: "Validation, schema, and best practices." },
  { id: "advanced", label: "Advanced", description: "JSON Schema, JSONPath, performance." },
  { id: "expert", label: "Expert Level", description: "Security, streaming, alternatives." },
];

const RESERVED_SLUGS = ["learn", "bundle", "api", "_next", "tools", "app"];

function generateLearn() {
  if (!fs.existsSync(LEARN_DIR)) {
    fs.writeFileSync(
      LEARN_OUT,
      `// Auto-generated - run npm run generate:content
export const LEARN_LEVELS = ${JSON.stringify(LEVELS, null, 2)} as const;
export const LEARN_SECTIONS: Array<{
  id: string; level: string; title: string; metaTitle?: string; metaDescription?: string;
  contentMarkdown: string; excerpt?: string; keyTerms: string[]; tryExample?: string;
}> = [];
`
    );
    return 0;
  }

  const files = fs.readdirSync(LEARN_DIR).filter((f) => f.endsWith(".md") && f !== "README.md");
  const sections = [];

  for (const file of files) {
    const id = file.replace(/\.md$/, "");
    const raw = fs.readFileSync(path.join(LEARN_DIR, file), "utf-8");
    const { data, content } = matter(raw);
    const rawContent = content.trim();
    const excerpt =
      data.excerpt ??
      rawContent
        .replace(/^#+ .+$/gm, "")
        .replace(/```[\s\S]*?```/g, "")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
        .replace(/[*_`]/g, "")
        .split(/\n\n/)[0]
        ?.slice(0, 200) ??
      "";

    sections.push({
      id,
      level: data.level ?? "beginner",
      title: data.title ?? id.replace(/-/g, " "),
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription,
      contentMarkdown: rawContent,
      excerpt: excerpt.trim() || undefined,
      keyTerms: Array.isArray(data.keyTerms) ? data.keyTerms.filter((t) => t != null) : [],
      tryExample: data.tryExample,
      publishedAt: data.publishedAt ?? null,
      _order: typeof data.order === "number" ? data.order : 999,
    });
  }

  sections.sort((a, b) => a._order - b._order);
  const out = sections.map(({ _order, ...section }) => section);

  const ts = `// Auto-generated by scripts/generate-content.cjs - do not edit
export const LEARN_LEVELS = ${JSON.stringify(LEVELS, null, 2)} as const;

export interface LearnSection {
  id: string;
  level: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
  excerpt?: string;
  keyTerms: string[];
  tryExample?: string;
  publishedAt?: string | null;
}

export const LEARN_SECTIONS: LearnSection[] = ${JSON.stringify(out, null, 2)};
`;

  fs.writeFileSync(LEARN_OUT, ts);
  return out.length;
}

function generatePages() {
  if (!fs.existsSync(PAGES_DIR)) {
    fs.writeFileSync(
      PAGES_OUT,
      `// Auto-generated - run npm run generate:content
export interface PageContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
}
export const PAGES: PageContent[] = [];
export const PAGE_SLUGS: string[] = [];
`
    );
    return 0;
  }

  const files = fs.readdirSync(PAGES_DIR).filter((f) => f.endsWith(".md") && f !== "README.md");
  const pages = [];

  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    if (RESERVED_SLUGS.includes(slug)) continue;
    const raw = fs.readFileSync(path.join(PAGES_DIR, file), "utf-8");
    const { data, content } = matter(raw);

    pages.push({
      slug,
      title: data.title ?? slug.replace(/-/g, " "),
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription,
      contentMarkdown: content.trim(),
    });
  }

  const ts = `// Auto-generated by scripts/generate-content.cjs - do not edit
export interface PageContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
}
export const PAGES: PageContent[] = ${JSON.stringify(pages, null, 2)};
export const PAGE_SLUGS: string[] = ${JSON.stringify(pages.map((page) => page.slug))};
`;

  fs.writeFileSync(PAGES_OUT, ts);
  return pages.length;
}

function readSiteFrontmatter(filePath) {
  if (!fs.existsSync(filePath)) return null;
  const raw = fs.readFileSync(filePath, "utf-8");
  const { data, content } = matter(raw);
  return { data, content: content.trim() };
}

function generateSite() {
  const homeParsed = readSiteFrontmatter(path.join(SITE_DIR, "home.md"));
  const toolsParsed = readSiteFrontmatter(path.join(SITE_DIR, "tools-index.md"));
  const learnParsed = readSiteFrontmatter(path.join(SITE_DIR, "learn-index.md"));

  const emptyHome = {
    title: "JSON Prism", metaTitle: undefined, metaDescription: undefined,
    heroEyebrow: undefined, heroTitle: undefined, heroDescription: undefined,
    primaryCtaLabel: undefined, primaryCtaHref: undefined,
    secondaryCtaLabel: undefined, secondaryCtaHref: undefined,
    trustPoints: [], faqs: [], contentMarkdown: "",
  };

  const home = homeParsed ? {
    title: homeParsed.data.title ?? "JSON Prism",
    metaTitle: homeParsed.data.metaTitle,
    metaDescription: homeParsed.data.metaDescription,
    heroEyebrow: homeParsed.data.heroEyebrow,
    heroTitle: homeParsed.data.heroTitle,
    heroDescription: homeParsed.data.heroDescription,
    primaryCtaLabel: homeParsed.data.primaryCtaLabel,
    primaryCtaHref: homeParsed.data.primaryCtaHref,
    secondaryCtaLabel: homeParsed.data.secondaryCtaLabel,
    secondaryCtaHref: homeParsed.data.secondaryCtaHref,
    trustPoints: Array.isArray(homeParsed.data.trustPoints) ? homeParsed.data.trustPoints : [],
    faqs: Array.isArray(homeParsed.data.faqs)
      ? homeParsed.data.faqs.map((faq) => ({ question: faq.question ?? "", answer: faq.answer ?? "" }))
      : [],
    contentMarkdown: homeParsed.content,
  } : emptyHome;

  const parseIndexPage = (parsed, defaults) => {
    if (!parsed) return defaults;
    return {
      title: parsed.data.title ?? defaults.title,
      heroEyebrow: parsed.data.heroEyebrow,
      heroTitle: parsed.data.heroTitle,
      heroDescription: parsed.data.heroDescription,
      tags: Array.isArray(parsed.data.tags) ? parsed.data.tags : [],
      whyTitle: parsed.data.whyTitle,
      whyBody: parsed.data.whyBody,
      contentMarkdown: parsed.content,
    };
  };

  const toolsIndex = parseIndexPage(toolsParsed, { title: "JSON Tools", tags: [] });
  const learnIndex = parseIndexPage(learnParsed, { title: "JSON Tutorial", tags: [] });

  const ts = `// Auto-generated by scripts/generate-content.cjs - do not edit
export interface SiteFaq {
  question: string;
  answer: string;
}

export interface HomeContent {
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroDescription?: string;
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  trustPoints: string[];
  faqs: SiteFaq[];
  contentMarkdown: string;
}

export interface IndexPageContent {
  title: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroDescription?: string;
  tags: string[];
  whyTitle?: string;
  whyBody?: string;
  contentMarkdown: string;
}

export const HOME_CONTENT: HomeContent = ${JSON.stringify(home, null, 2)};

export const TOOLS_INDEX_CONTENT: IndexPageContent = ${JSON.stringify(toolsIndex, null, 2)};

export const LEARN_INDEX_CONTENT: IndexPageContent = ${JSON.stringify(learnIndex, null, 2)};
`;

  fs.writeFileSync(SITE_OUT, ts);
  return 1;
}

function generateTools() {
  if (!fs.existsSync(TOOLS_DIR)) {
    fs.writeFileSync(
      TOOLS_OUT,
      `// Auto-generated - run npm run generate:content
export interface ToolContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  summary?: string;
  category?: string;
  appHref?: string;
  badge?: string;
  order: number;
  keywords: string[];
  highlights: string[];
  useCases: string[];
  faqs: Array<{ question: string; answer: string }>;
  contentMarkdown: string;
}
export const TOOLS: ToolContent[] = [];
export const TOOL_SLUGS: string[] = [];
`
    );
    return 0;
  }

  const files = fs.readdirSync(TOOLS_DIR).filter((f) => f.endsWith(".md") && f !== "README.md");
  const tools = [];

  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    const raw = fs.readFileSync(path.join(TOOLS_DIR, file), "utf-8");
    const { data, content } = matter(raw);

    tools.push({
      slug,
      title: data.title ?? slug.replace(/-/g, " "),
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription,
      summary: data.summary,
      category: data.category,
      appHref: data.appHref,
      badge: data.badge,
      order: typeof data.order === "number" ? data.order : 999,
      keywords: Array.isArray(data.keywords) ? data.keywords : [],
      highlights: Array.isArray(data.highlights) ? data.highlights : [],
      useCases: Array.isArray(data.useCases) ? data.useCases : [],
      faqs: Array.isArray(data.faqs)
        ? data.faqs.map((faq) => ({
            question: faq.question ?? "",
            answer: faq.answer ?? "",
          }))
        : [],
      contentMarkdown: content.trim(),
    });
  }

  tools.sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));

  const ts = `// Auto-generated by scripts/generate-content.cjs - do not edit
export interface ToolContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  summary?: string;
  category?: string;
  appHref?: string;
  badge?: string;
  order: number;
  keywords: string[];
  highlights: string[];
  useCases: string[];
  faqs: Array<{ question: string; answer: string }>;
  contentMarkdown: string;
}
export const TOOLS: ToolContent[] = ${JSON.stringify(tools, null, 2)};
export const TOOL_SLUGS: string[] = ${JSON.stringify(tools.map((tool) => tool.slug))};
`;

  fs.writeFileSync(TOOLS_OUT, ts);
  return tools.length;
}

const learnCount = generateLearn();
const pagesCount = generatePages();
const siteCount = generateSite();
const toolCount = generateTools();

console.log(
  `Generated: ${learnCount} learn sections, ${pagesCount} pages, ${siteCount} site file, ${toolCount} tool pages`
);
