/**
 * Build-time: reads content/learn/*.md and content/pages/*.md
 * Generates learn-sections.generated.ts and pages-content.generated.ts
 * No database — all content from markdown in the repo
 */
const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");

const ROOT = process.cwd();

// ─── Learn content ───────────────────────────────────────────────────────────
const LEARN_DIR = path.join(ROOT, "content", "learn");
const LEARN_OUT = path.join(ROOT, "src", "lib", "learn-sections.generated.ts");

const LEVELS = [
  { id: "beginner", label: "Basics for Beginners", description: "Never used JSON? Start here." },
  { id: "comfortable", label: "Getting Comfortable", description: "Understand structure and patterns." },
  { id: "practical", label: "Practical JSON", description: "Real-world usage and APIs." },
  { id: "intermediate", label: "Intermediate", description: "Validation, schema, and best practices." },
  { id: "advanced", label: "Advanced", description: "JSON Schema, JSONPath, performance." },
  { id: "expert", label: "Expert Level", description: "Security, streaming, alternatives." },
];

function generateLearn() {
  if (!fs.existsSync(LEARN_DIR)) {
    fs.writeFileSync(
      LEARN_OUT,
      `// Auto-generated - run npm run generate:content
export const LEARN_LEVELS = ${JSON.stringify(LEVELS, null, 2)} as const;
export const LEARN_SECTIONS: Array<{
  id: string; level: string; title: string; metaTitle?: string; metaDescription?: string;
  contentMarkdown: string; excerpt?: string; keyTerms: string[]; tryExample?: string;
}> = [];
`
    );
    return 0;
  }

  const files = fs.readdirSync(LEARN_DIR).filter((f) => f.endsWith(".md") && f !== "README.md");
  const sections = [];

  for (const file of files) {
    const id = file.replace(/\.md$/, "");
    const raw = fs.readFileSync(path.join(LEARN_DIR, file), "utf-8");
    const { data, content } = matter(raw);
    const rawContent = content.trim();
    const excerpt =
      data.excerpt ??
      rawContent
        .replace(/^#+ .+$/gm, "")
        .replace(/```[\s\S]*?```/g, "")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
        .replace(/[*_`]/g, "")
        .split(/\n\n/)[0]
        ?.slice(0, 200) ?? "";

    sections.push({
      id,
      level: data.level ?? "beginner",
      title: data.title ?? id.replace(/-/g, " "),
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription,
      contentMarkdown: rawContent,
      excerpt: excerpt.trim() || undefined,
      keyTerms: Array.isArray(data.keyTerms) ? data.keyTerms : [],
      tryExample: data.tryExample,
      _order: typeof data.order === "number" ? data.order : 999,
    });
  }

  sections.sort((a, b) => a._order - b._order);
  const out = sections.map(({ _order, ...s }) => s);

  const ts = `// Auto-generated by scripts/generate-content.cjs - do not edit
export const LEARN_LEVELS = ${JSON.stringify(LEVELS, null, 2)} as const;

export interface LearnSection {
  id: string;
  level: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
  excerpt?: string;
  keyTerms: string[];
  tryExample?: string;
}

export const LEARN_SECTIONS: LearnSection[] = ${JSON.stringify(out, null, 2)};
`;

  fs.writeFileSync(LEARN_OUT, ts);
  return out.length;
}

// ─── Pages content ───────────────────────────────────────────────────────────
const PAGES_DIR = path.join(ROOT, "content", "pages");
const PAGES_OUT = path.join(ROOT, "src", "lib", "pages-content.generated.ts");

const RESERVED_SLUGS = ["learn", "bundle", "api", "_next"];

function generatePages() {
  if (!fs.existsSync(PAGES_DIR)) {
    fs.writeFileSync(
      PAGES_OUT,
      `// Auto-generated - run npm run generate:content
export interface PageContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
}
export const PAGES: PageContent[] = [];
export const PAGE_SLUGS: string[] = [];
`
    );
    return 0;
  }

  const files = fs.readdirSync(PAGES_DIR).filter((f) => f.endsWith(".md") && f !== "README.md");
  const pages = [];

  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    if (RESERVED_SLUGS.includes(slug)) continue;
    const raw = fs.readFileSync(path.join(PAGES_DIR, file), "utf-8");
    const { data, content } = matter(raw);

    pages.push({
      slug,
      title: data.title ?? slug.replace(/-/g, " "),
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription,
      contentMarkdown: content.trim(),
    });
  }

  const ts = `// Auto-generated by scripts/generate-content.cjs - do not edit
export interface PageContent {
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  contentMarkdown: string;
}
export const PAGES: PageContent[] = ${JSON.stringify(pages, null, 2)};
export const PAGE_SLUGS: string[] = ${JSON.stringify(pages.map((p) => p.slug))};
`;

  fs.writeFileSync(PAGES_OUT, ts);
  return pages.length;
}

// ─── Run ─────────────────────────────────────────────────────────────────────
const learnCount = generateLearn();
const pagesCount = generatePages();
console.log(`Generated: ${learnCount} learn sections, ${pagesCount} pages`);
process.exit(0);
